export const FETCH_TOP_NEWS_IN_PROGRESS = 'FETCH_TOP_NEWS_IN_PROGRESS';
export const FETCH_TOP_NEWS_SUCCESS = 'FETCH_TOP_NEWS_SUCCESS';
export const FETCH_TOP_NEWS_ERROR = 'FETCH_TOP_NEWS_ERROR';

export const FETCH_SECTION_NEWS_IN_PROGRESS = 'FETCH_SECTION_NEWS_IN_PROGRESS';
export const FETCH_SECTION_NEWS_SUCCESS = 'FETCH_SECTION_NEWS_SUCCESS';
export const FETCH_SECTION_NEWS_ERROR = 'FETCH_SECTION_NEWS_ERROR';
