export const FETCH_BOOKMARKS_IN_PROGRESS = 'FETCH_BOOKMARKS_IN_PROGRESS';
export const FETCH_BOOKMARKS_SUCCESS = 'FETCH_BOOKMARKS_SUCCESS';
export const FETCH_BOOKMARKS_ERROR = 'FETCH_BOOKMARKS_ERROR';

export const ADD_BOOKMARK_IN_PROGRESS = 'ADD_BOOKMARK_IN_PROGRESS';
export const ADD_BOOKMARK_SUCCESS = 'ADD_BOOKMARK_SUCCESS';
export const ADD_BOOKMARK_ERROR = 'ADD_BOOKMARK_ERROR';

export const REMOVE_BOOKMARK_IN_PROGRESS = 'REMOVE_BOOKMARK_IN_PROGRESS';
export const REMOVE_BOOKMARK_SUCCESS = 'REMOVE_BOOKMARK_SUCCESS';
export const REMOVE_BOOKMARK_ERROR = 'REMOVE_BOOKMARK_ERROR';

export const SORT_BOOKMARKS = 'SORT_BOOKMARKS';
