export const SET_LOADING = 'SET_LOADING';
export const SEARCH_NEWS_IN_PROGRESS = 'SEARCH_NEWS_IN_PROGRESS';
export const SEARCH_NEWS_SUCCESS = 'SEARCH_NEWS_SUCCESS';
export const SEARCH_NEWS_ERROR = 'SEARCH_NEWS_ERROR';
export const RESET_SEARCH_NEWS = 'RESET_SEARCH_NEWS';
