export const FETCH_TOP_NEWS_IN_PROGRESS = "FETCH_TOP_NEWS_IN_PROGRESS";
export const FETCH_TOP_NEWS_SUCCESS = "FETCH_TOP_NEWS_SUCCESS";
export const FETCH_TOP_NEWS_ERROR = "FETCH_TOP_NEWS_ERROR";

export const FETCH_SPORTS_NEWS_IN_PROGRESS = "FETCH_SPORTS_NEWS_IN_PROGRESS";
export const FETCH_SPORTS_NEWS_SUCCESS = "FETCH_SPORTS_NEWS_SUCCESS";
export const FETCH_SPORTS_NEWS_ERROR = "FETCH_SPORTS_NEWS_ERROR";

export const SEARCH_NEWS_IN_PROGRESS = "SEARCH_NEWS_IN_PROGRESS";
export const SEARCH_NEWS_SUCCESS = "SEARCH_NEWS_SUCCESS";
export const SEARCH_NEWS_ERROR = "SEARCH_NEWS_ERROR";

