export const FETCH_TOP_NEWS_IN_PROGRESS = 'FETCH_TOP_NEWS_IN_PROGRESS';
export const FETCH_TOP_NEWS_SUCCESS = 'FETCH_TOP_NEWS_SUCCESS';
export const FETCH_TOP_NEWS_ERROR = 'FETCH_TOP_NEWS_ERROR';

export const FETCH_SECTION_NEWS_IN_PROGRESS = 'FETCH_SECTION_NEWS_IN_PROGRESS';
export const FETCH_SECTION_NEWS_SUCCESS = 'FETCH_SECTION_NEWS_SUCCESS';
export const FETCH_SECTION_NEWS_ERROR = 'FETCH_SECTION_NEWS_ERROR';

export const SEARCH_NEWS_IN_PROGRESS = 'SEARCH_NEWS_IN_PROGRESS';
export const SEARCH_NEWS_SUCCESS = 'SEARCH_NEWS_SUCCESS';
export const SEARCH_NEWS_ERROR = 'SEARCH_NEWS_ERROR';

export const RESET_SEARCH_NEWS = 'RESET_SEARCH_NEWS';
